spring.application.name=digitalmemorycapsuleAPI
spring.datasource.url=jdbc:mysql://localhost:3306/capsule_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=2005